---
linters:
  enable-all: true
  disable:
    # Deprecated
    - deadcode
    - ifshort
    - scopelint
    - maligned
    - golint
    - varcheck
    - nosnakecase
    - structcheck
    - interfacer
    - exhaustivestruct
    # Conflicts with gofmt
    - wsl
    # I do like some empty structs
    - exhaustruct
    # Although useful, sometimes I need to return with errors before ending the functions
    - wrapcheck
    # Since I'm not making a package in itself, no need for a specific test sub-package
    - testpackage

linters-settings:
  # Packages allowed
  depguard:
    rules:
      prevent_unmaintained_packages:
        list-mode: lax # allow unless explicitly denied
        files:
          - $all
          - $test
        allow:
          - $gostd
          - github.com/stretchr/testify/suite
          - github.com/mattn/go-sqlite3
          - github.com/redds-be/redd-go-template/internal/ports
          - github.com/redds-be/redd-go-template/internal/application/core/helloworld
          - github.com/redds-be/redd-go-template/internal/framework/out/database
          - github.com/redds-be/redd-go-template/internal/framework/in/http
          - github.com/redds-be/redd-go-template/internal/application/api
        deny:
          - pkg: io/ioutil
            desc: "replaced by io and os packages since Go 1.16: https://tip.golang.org/doc/go1.16#ioutil"
  # Default values conflicts with gofmt
  lll:
    line-length: 160
    tab-width: 1