---
linters:
  enable-all: true
  disable:
    # Deprecated
    - deadcode
    - ifshort
    - scopelint
    - maligned
    - golint
    - varcheck
    - nosnakecase
    - structcheck
    - interfacer
    - exhaustivestruct
    # Conflicts with gofmt
    - wsl
    # I do like some empty structs
    - exhaustruct
    # Although useful, sometimes I need to return with errors before ending the functions
    - wrapcheck
    # I need some globals
    - gochecknoglobals

linters-settings:
  # Packages allowed
  depguard:
    rules:
      prevent_unmaintained_packages:
        list-mode: lax # allow unless explicitly denied
        files:
          - $all
          - $test
        allow:
          - $gostd
          - github.com/redds-be/rpkgm/cmd
          - github.com/redds-be/rpkgm/internal/pkg
          - github.com/redds-be/rpkgm/internal/util
          - github.com/redds-be/rpkgm/internal/pkg
          - github.com/redds-be/rpkgm/internal/database
          - github.com/redds-be/rpkgm/internal/logging
          - github.com/spf13/cobra
          - github.com/google/uuid
          - github.com/mattn/go-sqlite3
  # Default values conflicts with gofmt
  lll:
    line-length: 160
    tab-width: 1
