name: gobuild

on: [push]

permissions:
  contents: read

jobs:
  gobuild:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          cache: false
      - name: Build the project
        run: |
          go build main.go
